Added a quick fix for tetrad array element selection bug.
mbitson/mcg pull request #105
Opened 2019-01-28 15:34 UTC by tabuckner

Discovered this while making a SASS adaptation of your approach. Thank you so much for making this open source!

`tinycolor.tetrad()` returns an array with a length of 4. Targeting index `[4]` returns `undefined`. `tinycolor.mix()` does not complain about an undefined value for argument 2, but we're not correctly handling the mix approach. 

Using @angular/material as a baseline, I tweaked the values to somewhat more closely match the `mat-indigo` palette.

```javascript
// @angular/material mat-indigo palette
mat-indigo = {
  50: #e8eaf6,
  100: #c5cae9,
  200: #9fa8da,
  300: #7986cb,
  400: #5c6bc0,
  500: #3f51b5,
  600: #3949ab,
  700: #303f9f,
  800: #283593,
  900: #1a237e,
  A100: #8c9eff,
  A200: #536dfe,
  A400: #3d5afe,
  A700: #304ffe
};
```

```javascript
// new output with same base color
testMap = {
  50: #e8eaf6,
  100: #c5cbe9,
  200: #9fa8da,
  300: #7985cb,
  400: #5c6bc0,
  500: #3f51b5,
  600: #394aae,
  700: #3140a5,
  800: #29379d,
  900: #1b278d,
  A100: #88a6ff,
  A200: #4b79ff,
  A400: #3166ff,
  A700: #225aff
};
```

2019-01-28 16:38 UTC, mbitson commented
Hey @tabuckner !

Thank you so much for your interest in the project and your commit here! You're adjusting one of the particular color algorithms, where instead you should be making a third algorithm option for the settings. At that point we'd need to adjust the if{}else{} statement to be more robust and call any one of the three possible algorithms for color generation.

If we did that I'd go ahead and merge this in. I don't have a lot of time lately, but I may come back and help adjust.

Thanks!

2019-01-28 16:38 UTC, mbitson requested changes
Hey @tabuckner !

Thank you so much for your interest in the project and your commit here! You're adjusting one of the particular color algorithms, where instead you should be making a third algorithm option for the settings. At that point we'd need to adjust the if{}else{} statement to be more robust and call any one of the three possible algorithms for color generation.

If we did that I'd go ahead and merge this in. I don't have a lot of time lately, but I may come back and help adjust.

Thanks!

2019-01-28 16:40 UTC, tabuckner commented
@mbitson sure, i can do that! One sec

2019-01-28 17:02 UTC, tabuckner commented
@mbitson made a few changes, and I think this oughta do the trick:

![image](https://user-images.githubusercontent.com/32392635/51852686-3480e700-22ec-11e9-8266-85d4583aea7e.png)

2019-01-29 02:24 UTC, mbitson approved these changes
Hey @tabuckner !

Impressive work, thank you sir! 

I'll get this deployed to my copy of the tool soon.

2019-01-29 13:33 UTC, tabuckner commented
@mbitson No worries :], I'm glad I was able to contribute! You helped me out of a bind by making this OS!

2020-04-29 01:58 UTC, mbitson approved these changes

2020-04-29 01:58 UTC, merged

2020-04-29 01:59 UTC, mbitson commented
Thank you again for this fix, @tabuckner ! Getting this repo cleaned up and this is helpful!

2020-04-29 02:18 UTC, tabuckner commented
Of course!! Thank you for what you've done!

Let me know if you want any help I'd love to give back 😄